### PR TITLE
Feature/feature change username

### PR DESCRIPTION
**Pull request by santidrj**

### CODE REVIEW

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/org/pesmypetcare/webservice/controller/usermanager/UserRestController.java  1
         

Clones added
============
- src/test/java/org/pesmypetcare/webservice/dao/UserDaoTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5361517&bid=17568015)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/org/pesmypetcare/webservice/controller/usermanager/UserRestController.java  1
         

Clones added
============
- src/test/java/org/pesmypetcare/webservice/dao/UserDaoTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5361517&bid=17568015)

**Review by AlbertPG — APPROVED** [review]
Okey, I see no problems at all

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/org/pesmypetcare/webservice/controller/usermanager/UserRestController.java  1
         

Clones added
============
- src/test/java/org/pesmypetcare/webservice/dao/UserDaoTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5361517&bid=17568015)

**Review by marclll — APPROVED** [review]

**Pull request merged**
